version: '3'
services:
  activemq:
    image: rmohr/activemq
    container_name: activemq
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    ports:
      - "61616:61616"
      - "8161:8161"
    volumes:
      - activemq-data:/opt/activemq/data
      - activemq-logs:/var/log/activemq

volumes:
  activemq-data:
  activemq-logs:
