server:
  port: 8189
spring:
  application:
    name: java-pro-spring
  datasource:
    url: jdbc:h2:mem:mydb;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  data:
    jdbc:
      dialect: h2
  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-on-validation-error: true